kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hyp-es
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: snap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyp-es
  labels:
    app: hyp-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyp-es
  template:
    metadata:
      labels:
        app: hyp-es
    spec:
      containers:
      - name: hyp-es
        image: hypothesis/elasticsearch:latest
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: hyp-es
        livenessProbe:
          httpGet:
            port: http
            path: /_cluster/health
          initialDelaySeconds: 40
          periodSeconds: 60
        ports:
        - containerPort: 9200
          name: http
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx200m -Xms200m
      volumes:
      - name: hyp-es
        persistentVolumeClaim:
          claimName: hyp-es
---
apiVersion: v1
kind: Service
metadata:
  name: hyp-es
spec:
  selector:
    app: hyp-es
  ports:
    - protocol: TCP
      port: 9200
      name: http
